export const URL = {
  HOST_CHANGED: 'URL-HOST_CHANGED',
  PORT_CHANGED: 'URL-PORT_CHANGED',
};


export const PROTO = {
  LOAD: 'PROTO-LOAD',
  STUB_SELECTED: 'PROTO-STUB_SELECTED',
  CALL_SELECTED: 'PROTO-CALL_SELECTED',
};


export const RPC = {
  REQUEST_CHANGED: 'RPC-REQUEST_CHANGED',
  RESPONSE_RECEIVED: 'RPC-RESPONSE_RECEIVED',
  PREPARE_CALL: 'RPC-PREPARE_CALL',
};
